url: https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-3.10.0.tgz
version: 100.3.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
