url: https://github.com/epinio/helm-charts/releases/download/epinio-1.8.1/epinio-1.8.1.tgz
version: 102.0.3
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
