url: https://github.com/epinio/helm-charts/releases/download/epinio-1.6.2/epinio-1.6.2.tgz
version: 100.0.5
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
