url: https://github.com/epinio/helm-charts/releases/download/epinio-1.2.1/epinio-1.2.1.tgz
version: 100.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
