auto: true
url: https://github.com/rancher/cis-operator.git
chartRepoBranch: release/v1.3
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/cis-operator.git
      chartRepoBranch: release/v1.3
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true