url: https://neuvector.github.io/neuvector-helm/core-2.2.4.tgz
version: 100.0.3
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
