url: https://neuvector.github.io/neuvector-helm/core-2.4.3.tgz
version: 100.0.4
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
