url: https://neuvector.github.io/neuvector-helm/core-2.8.3.tgz
version: 103.0.7
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
