url: https://neuvector.github.io/neuvector-helm/core-2.4.5.tgz
version: 100.0.5
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
