name: Auto Chart Bump

on:
  workflow_call:
    inputs:
      eventPayload:
        description: "Payload data from upstream repository"
        required: true
        type: string

jobs:
  process-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log Event Payload
        run: |
         echo "Payload: ${{  github.event.inputs.chart  }}; ${{  github.event.inputs.branch  }}"

      - name: Parse JSON Payload
        id: parse_payload
        run: |
          echo "CHART=${{ github.event.inputs.chart }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV

      - name: Checkout to new branch
        run: |
          git checkout -b "auto-bump_${{ env.CHART }}"

      - name: make chart-bump
        run: |
          echo "make chart-bump package=${{ env.CHART }} branch=${{ env.BRANCH }}"
          make chart-bump package="${{ env.CHART }}" branch="${{ env.BRANCH }}"

      - name: Git status
        run: |
          git status
          if [ -z "$(git status --porcelain)" ]; then
            echo "No bump detected"
            exit 1
          fi

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Git Add, Commit, Push Changes
        run: |
          git add .
          git commit -m "Auto bump chart version for ${{ env.CHART }}"
          git push origin ${{ env.BRANCH }}

      - name: Create Pull Request
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh pr create --base ${{ env.BRANCH }} --head "auto-bump_${{ env.CHART }}" --title "[${{ env.BRANCH }}] auto bump: ${{ env.CHART }}" --body "This PR auto-bumps the chart version for ${{ env.CHART }}"
