name: Auto Chart Bump

on:
  workflow_call:
    inputs:
      eventPayload:
        description: "Payload data from upstream repository"
        required: true
        type: string

jobs:
  process-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log Event Payload
        run: |
         echo "Raw Payload: ${{ github.event.inputs.eventPayload }}"

      - name: Parse JSON Payload
        id: parse_payload
        run: |
          echo '${{ github.event.inputs.eventPayload }}' | jq -r '.chart, .branch' | {
            read chart
            read branch
            echo "CHART=$chart" >> $GITHUB_ENV
            echo "BRANCH=$branch" >> $GITHUB_ENV
          }

      - name: make chart-bump
        run: |
          echo "make chart-bump package=${{ env.CHART }} branch=${{ env.BRANCH }}"
          make chart-bump package="${{ env.CHART }}" branch="${{ env.BRANCH }}"

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Git Add, Commit, Push Changes
        run: |
          git add .
          git commit -m "Auto bump chart version for ${{ env.CHART }}"
          git push origin ${{ env.BRANCH }}

      - name: Create Pull Request
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh pr create --base ${{ env.BRANCH }} --head ${{ github.sha }} --title "[${{ env.BRANCH }}] auto bump: ${{ env.CHART }}" --body "This PR auto-bumps the chart version for ${{ env.CHART }}"

